import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Electronics (8 products)
        {
            name: 'Apple iPhone 14 Pro Max 256GB Deep Purple',
            description: 'Latest iPhone with Dynamic Island, A16 Bionic chip, Pro camera system with 48MP main lens, and all-day battery life.',
            price: 1099.99,
            category: 'Electronics',
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1678652197950-6c1ae01d8d1f?w=800&q=80',
            sellerId: 1,
            createdAt: new Date('2024-10-15').toISOString(),
        },
        {
            name: 'Samsung 55-inch 4K QLED Smart TV',
            description: 'Crystal-clear 4K resolution with Quantum Dot technology, HDR support, smart hub with streaming apps, and voice control.',
            price: 799.99,
            category: 'Electronics',
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80',
            sellerId: 2,
            createdAt: new Date('2024-10-20').toISOString(),
        },
        {
            name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
            description: 'Industry-leading noise cancellation, 30-hour battery life, premium comfort, crystal-clear calls, and multipoint connection.',
            price: 399.99,
            category: 'Electronics',
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
            sellerId: 3,
            createdAt: new Date('2024-10-25').toISOString(),
        },
        {
            name: 'Apple iPad Air 5th Gen 64GB Wi-Fi Space Gray',
            description: 'Powerful M1 chip, stunning 10.9-inch Liquid Retina display, Touch ID, compatible with Apple Pencil and Magic Keyboard.',
            price: 599.99,
            category: 'Electronics',
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
            sellerId: 4,
            createdAt: new Date('2024-11-01').toISOString(),
        },
        {
            name: 'Canon EOS R6 Mark II Mirrorless Camera Body',
            description: 'Professional 24.2MP full-frame sensor, 40fps continuous shooting, 6K video recording, advanced autofocus system.',
            price: 2499.99,
            category: 'Electronics',
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80',
            sellerId: 5,
            createdAt: new Date('2024-11-05').toISOString(),
        },
        {
            name: 'Apple Watch Series 9 GPS 45mm Midnight Aluminum',
            description: 'Advanced health tracking, ECG, blood oxygen monitoring, always-on Retina display, water resistant, cellular connectivity.',
            price: 429.99,
            category: 'Electronics',
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&q=80',
            sellerId: 1,
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            name: 'PlayStation 5 Console with Spider-Man 2 Bundle',
            description: 'Next-gen gaming with ultra-high-speed SSD, stunning 4K graphics, haptic feedback, adaptive triggers, and exclusive games.',
            price: 549.99,
            category: 'Electronics',
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&q=80',
            sellerId: 2,
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            name: 'Apple AirPods Pro 2nd Generation with MagSafe',
            description: 'Active noise cancellation, transparency mode, adaptive audio, spatial audio, up to 6 hours listening time, wireless charging.',
            price: 249.99,
            category: 'Electronics',
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=800&q=80',
            sellerId: 3,
            createdAt: new Date('2024-11-20').toISOString(),
        },

        // Home & Garden (6 products)
        {
            name: 'Modern Mid-Century Velvet Sofa 3-Seater Navy Blue',
            description: 'Comfortable velvet upholstery, solid wood frame, tufted backrest, perfect for living room, easy assembly included.',
            price: 899.99,
            category: 'Home & Garden',
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
            sellerId: 4,
            createdAt: new Date('2024-11-25').toISOString(),
        },
        {
            name: 'Fiddle Leaf Fig Tree 6ft Indoor Plant with Decorative Pot',
            description: 'Live indoor plant, air purifying, low maintenance, comes in premium ceramic pot, perfect for home or office decoration.',
            price: 89.99,
            category: 'Home & Garden',
            rating: 4.3,
            imageUrl: 'https://images.unsplash.com/photo-1463154545680-d59320fd685d?w=800&q=80',
            sellerId: 5,
            createdAt: new Date('2024-12-01').toISOString(),
        },
        {
            name: 'DeWalt 20V Cordless Drill and Impact Driver Combo Kit',
            description: 'Professional-grade power tools, includes 2 batteries, charger, carrying case, LED work lights, and multiple drill bits.',
            price: 199.99,
            category: 'Home & Garden',
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&q=80',
            sellerId: 1,
            createdAt: new Date('2024-12-05').toISOString(),
        },
        {
            name: 'Bohemian Macrame Wall Hanging Tapestry 36x48 inches',
            description: 'Handmade cotton macrame, boho chic design, perfect for bedroom or living room, includes hanging rod and installation kit.',
            price: 49.99,
            category: 'Home & Garden',
            rating: 4.4,
            imageUrl: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800&q=80',
            sellerId: 2,
            createdAt: new Date('2024-12-10').toISOString(),
        },
        {
            name: 'KitchenAid Artisan Stand Mixer 5-Quart Empire Red',
            description: 'Professional mixing performance, 10 speed settings, tilt-head design, includes whisk, dough hook, and flat beater.',
            price: 449.99,
            category: 'Home & Garden',
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1578991624414-276ef23a534f?w=800&q=80',
            sellerId: 3,
            createdAt: new Date('2024-12-15').toISOString(),
        },
        {
            name: 'Modular Cube Storage Organizer 16-Cube White',
            description: 'Versatile storage solution, easy assembly, includes fabric bins, perfect for closet, bedroom, or living room organization.',
            price: 79.99,
            category: 'Home & Garden',
            rating: 4.2,
            imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
            sellerId: 4,
            createdAt: new Date('2024-12-20').toISOString(),
        },

        // Fashion (6 products)
        {
            name: 'Levi\'s 501 Original Fit Men\'s Jeans Dark Wash',
            description: 'Classic straight fit, button fly, premium denim, timeless style, durable construction, available in multiple sizes.',
            price: 79.99,
            category: 'Fashion',
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80',
            sellerId: 5,
            createdAt: new Date('2024-12-25').toISOString(),
        },
        {
            name: 'Nike Air Max 270 React Running Shoes Black White',
            description: 'Responsive cushioning, breathable mesh upper, durable rubber outsole, modern design, perfect for running and everyday wear.',
            price: 149.99,
            category: 'Fashion',
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
            sellerId: 1,
            createdAt: new Date('2024-12-28').toISOString(),
        },
        {
            name: 'Michael Kors Jet Set Travel Leather Tote Bag Brown',
            description: 'Genuine leather, multiple compartments, top zip closure, gold-tone hardware, perfect for work or travel, elegant design.',
            price: 299.99,
            category: 'Fashion',
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80',
            sellerId: 2,
            createdAt: new Date('2025-01-02').toISOString(),
        },
        {
            name: 'Fossil Gen 6 Hybrid Smartwatch Stainless Steel',
            description: 'Classic analog design with smart features, activity tracking, notifications, 2-week battery life, water resistant.',
            price: 229.99,
            category: 'Fashion',
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
            sellerId: 3,
            createdAt: new Date('2025-01-05').toISOString(),
        },
        {
            name: 'Ray-Ban Aviator Classic Sunglasses Gold Frame Green Lens',
            description: 'Iconic aviator style, 100% UV protection, lightweight metal frame, adjustable nose pads, includes case and cloth.',
            price: 159.99,
            category: 'Fashion',
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80',
            sellerId: 4,
            createdAt: new Date('2025-01-08').toISOString(),
        },
        {
            name: 'Patagonia Better Sweater Fleece Jacket Navy Blue',
            description: 'Sustainable fleece, warm and comfortable, zippered pockets, raglan sleeves, perfect for outdoor activities and casual wear.',
            price: 139.99,
            category: 'Fashion',
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80',
            sellerId: 5,
            createdAt: new Date('2025-01-10').toISOString(),
        },

        // Sports (5 products)
        {
            name: 'Bowflex SelectTech 552 Adjustable Dumbbells Pair',
            description: 'Adjustable weight from 5 to 52.5 lbs per dumbbell, space-saving design, quick weight changes, perfect for home gym.',
            price: 349.99,
            category: 'Sports',
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
            sellerId: 1,
            createdAt: new Date('2025-01-12').toISOString(),
        },
        {
            name: 'Manduka PRO Yoga Mat 71-inch Black Sage',
            description: 'Professional-grade yoga mat, dense cushioning, excellent grip, non-slip surface, eco-friendly materials, lifetime guarantee.',
            price: 119.99,
            category: 'Sports',
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80',
            sellerId: 2,
            createdAt: new Date('2025-01-14').toISOString(),
        },
        {
            name: 'Coleman Sundome 4-Person Camping Tent',
            description: 'Weather-resistant, easy setup, large windows for ventilation, spacious interior, includes carry bag, perfect for family camping.',
            price: 89.99,
            category: 'Sports',
            rating: 4.4,
            imageUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80',
            sellerId: 3,
            createdAt: new Date('2025-01-16').toISOString(),
        },
        {
            name: 'Adidas Tiro 21 Training Pants Black White Stripes',
            description: 'Moisture-wicking fabric, tapered fit, zippered pockets, ankle zips, perfect for training and casual wear, breathable material.',
            price: 44.99,
            category: 'Sports',
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&q=80',
            sellerId: 4,
            createdAt: new Date('2025-01-18').toISOString(),
        },
        {
            name: 'REI Co-op Trail 40 Hiking Backpack',
            description: 'Lightweight design, adjustable suspension, multiple pockets, hydration compatible, breathable back panel, rain cover included.',
            price: 149.99,
            category: 'Sports',
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1622260614153-03223fb72052?w=800&q=80',
            sellerId: 5,
            createdAt: new Date('2025-01-20').toISOString(),
        },

        // Books (3 products)
        {
            name: 'Atomic Habits by James Clear Hardcover',
            description: 'Practical strategies for forming good habits, breaking bad ones, and mastering tiny behaviors. Bestselling self-improvement book.',
            price: 24.99,
            category: 'Books',
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&q=80',
            sellerId: 1,
            createdAt: new Date('2025-01-22').toISOString(),
        },
        {
            name: 'Campbell Biology 12th Edition College Textbook',
            description: 'Comprehensive biology textbook, latest edition, includes access code for online resources, perfect for college students.',
            price: 189.99,
            category: 'Books',
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&q=80',
            sellerId: 2,
            createdAt: new Date('2025-01-24').toISOString(),
        },
        {
            name: 'The Amazing Spider-Man Omnibus Vol. 1 Marvel Comics',
            description: 'Collects early Spider-Man stories, high-quality printing, premium binding, classic artwork, perfect for collectors.',
            price: 89.99,
            category: 'Books',
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=800&q=80',
            sellerId: 3,
            createdAt: new Date('2025-01-25').toISOString(),
        },

        // Tools (4 products)
        {
            name: 'Milwaukee M18 Fuel Hammer Drill Driver Kit',
            description: 'Brushless motor, 1200 in-lbs torque, all-metal chuck, LED light, includes 2 batteries, charger, and contractor bag.',
            price: 299.99,
            category: 'Tools',
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800&q=80',
            sellerId: 4,
            createdAt: new Date('2025-01-26').toISOString(),
        },
        {
            name: 'Craftsman 230-Piece Mechanics Tool Set with Case',
            description: 'Complete tool set with sockets, wrenches, screwdrivers, pliers, includes durable carrying case, lifetime warranty.',
            price: 149.99,
            category: 'Tools',
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&q=80',
            sellerId: 5,
            createdAt: new Date('2025-01-27').toISOString(),
        },
        {
            name: 'Husky 72-inch Mobile Workbench with Solid Wood Top',
            description: 'Heavy-duty steel construction, adjustable height, 6 drawers, pegboard back, locking casters, perfect for garage workshop.',
            price: 399.99,
            category: 'Tools',
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&q=80',
            sellerId: 1,
            createdAt: new Date('2025-01-28').toISOString(),
        },
        {
            name: 'Bosch 12V Max 3-Tool Combo Kit',
            description: 'Includes drill/driver, impact driver, and LED worklight, compact design, 2 batteries, charger, and soft carrying bag.',
            price: 179.99,
            category: 'Tools',
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800&q=80',
            sellerId: 2,
            createdAt: new Date('2025-01-29').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});